### ISSUE TITLE
Codecrumbs hasn't launched on Python project

### ISSUE THREAD

**Issue by trkohler** [Bogdan-Lyashenko/codecrumbs#96]
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs-readdir-recursive'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/t.kohler/.config/yarn/global/node_modules/codecrumbs/src/server/code-parse/language/php/namespaces.js:1:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
Hi!
Tried to launch the codecrumbs on the Python project and got this. 
May I ask for suggestions to fix this?

**Comment by Bogdan-Lyashenko** [comment]
Hi. Which version of codecrumbs do you run? What OS/Nodejs do you have? Can you show how do you run it? Is it only for that specific project or it doesn’t work for you with any project? Thanks!

**Comment by trkohler** [comment]
```
~  codecrumbs -v
error: unknown option `-v'
~  codecrumbs -V
error: unknown option `-V'
~  codecrumbs --version
error: unknown option `--version'
~  codecrumbs
Please specify `entryPoint` and `projectDir` params (e.g. `codecrumbs -e src/app.js -d src`). Or use `-C codecrumbs.config.js` instead.
```

how can i discover what version of codecrumbs do I have?

**Comment by Bogdan-Lyashenko** [comment]
I was asking more like, if you use v1 or v2 🙂  I guess v1 (hence CLI params). Can you try v2 intsead, i.e. desktop app instead of CLI tool? v1 is no longer supported and v2 got bunch of new cool features (it's free).

**Comment by trkohler** [comment]
sounds cool! where can i find about installation the V2?

I have used this instruction 
```
yarn global add codecrumbs
```
from **readme.md**

**Comment by Bogdan-Lyashenko** [comment]
Everything on the website 🤓You can start from this guide https://codecrumbs.io/guides/web-app-with-github. Let me know if need help. Thanks!
